# Configuration file to run WhaleMoanDetector and modify file paths
#Michaela Alksne
# define file paths:
wav_directory: '/media/kasey/LEXAR'
txt_file_path: '/home/kasey/Desktop/Outputs_WhaleDet/test_pi_detections.txt'
model_path: '//home/kasey/Desktop/WhaleMoanDetector/WhaleMoanDetector_12_11_24_12_best.pth'
CalCOFI_flag: False # True or False
