# Configuration file to run WhaleMoanDetector and modify file paths
#Michaela Alksne
# define file paths:
wav_directory: 'Q:/CalCOFI 2004/CalCOFI 2004-07/57BSonobuoys/decimated'
txt_file_path: 'L:/WhaleMoanDetector_predictions/CalCOFI_2004/CalCOFI_2004_07/CalCOFI_2004_07_raw_detections.txt'
model_path: 'L:/WhaleMoanDetector/models/WhaleMoanDetector_12_11_24_12_best.pth'
CalCOFI_flag: True # True or False
