# Configuration file to run WhaleMoanDetector and modify file paths
#Michaela Alksne

wav_directory: 'L:/CHNMS_audio/CHNMS_NO_01'
csv_file_path: 'L:/WhaleMoanDetector_predictions/CHNMS/CHNMS_NO_01/CHNMS_NO_01_raw_detections.csv'
model_path: 'L:/WhaleMoanDetector/models/WhaleMoanDetector.pth'

