# Configuration file to run WhaleMoanDetector and modify file paths
#Michaela Alksne
# define file paths:
wav_directory: 'L:/WhaleMoanDetector/labeled_data/wav/SOCAL34N'
txt_file_path: 'L:/WhaleMoanDetector_predictions/SOCAL34N/SOCAL34N_raw_detections.txt'
model_path: 'L:/WhaleMoanDetector/models/WhaleMoanDetector_12_11_24_12_best.pth'
CalCOFI_flag: False # True or False
