# Configuration file to run WhaleMoanDetector and modify file paths
#Michaela Alksne
# define file paths:
wav_directory: ''
txt_file_path: '/home/kasey/Desktop/WhaleDet_Test_6_19\output.txt'
model_path: '/home/kasey/Desktop/WhaleMoanDetector_12_11_24_12_best.pth'
CalCOFI_flag: False # True or False
listen_port: '192.168.1.235'
